language: java
jdk:
  - oraclejdk8
sudo: false
install: true

script:
  - ./gradlew check --info

# cache gradle dependencies
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
