language: java
group: edge
jdk:
  - oraclejdk8
  - oraclejdk9
sudo: false
install: true

script:
  - ./gradlew check --info

# cache gradle dependencies
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
